#!/bin/bash
volume=$(pamixer --get-volume)
volume=$(($volume + 0))
if [[ $volume -lt 33 ]]
then
    icon=
elif [[ $volume -lt 66 ]]
then
    icon=
else
    icon=
fi
if [[ $(pamixer --get-volume-human) = "muted" ]]
then
    icon="%{F$(colorer -g color8)}%{F-}"
fi
echo $icon
