#!/bin/bash
script_dir=$(dirname $0)
theme=$1
files=$(find $script_dir/$theme -type f -exec bash -c "echo {} | sed 's/.*\($theme\)\///g'" \;)
files_to_treat=$(echo "$files" | xargs -I FILE bash -c "test -f ~/FILE && { cmp ~/FILE $script_dir/$theme/FILE >/dev/null || echo FILE; }")

echo -e "\033[1mFiles to be copied:\033[0m"
echo "$files_to_treat" | xargs -I FILE bash -c "echo ~/FILE -\> $script_dir/$theme/FILE"
if [ "${2}" != "-n" ]; then
    echo -e "\033[1mCopying files...\033[0m"
    echo "$files_to_treat" | xargs -I FILE bash -c "cp ~/FILE $script_dir/$theme/FILE"
else
    echo -e "\033[1mDry run, no changes made.\033[0m"
fi

echo -e "\033[1mChecking diff in directories.\033[0m"
directories=$(find $script_dir/$theme -type d -exec bash -c "echo {} | sed 's/.*\($theme\)\///g'" \;)
echo "$directories" | xargs -I FILE bash -c "diff -qr ~/FILE $script_dir/$theme/FILE"
