#!/bin/bash
if [[ "$1" = "up" ]]
then
    pamixer -i $2
elif [[ "$1" = "down" ]]
then
    pamixer -d $2
else
    echo "No argument/wrong arguments"
    exit 1
fi
volume=$(pamixer --get-volume)
dunstify "Volume" "Volume: ${volume}%" -h int:value:$volume -h string:x-dunst-stack-tag:volume 
