#! /bin/sh

sxhkd &

# wm config
bspc config border_width 1
bspc config window_gap 25
out=0
# bspc config top_padding $(( $(polybar --dump=height base 2>/dev/null) + $(polybar --dump=offset-y base 2>/dev/null)+ $out + $(bspc config window_gap)))
bspc config bottom_padding $(( $(polybar --dump=height base 2>/dev/null) + $(polybar --dump=offset-y base 2>/dev/null)+ $out))
bspc config split_ratio          0.50

bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4 5

# rules
bspc rule -a Zathura state=tiled

inactive=$(colorer -g bg)
active=$(colorer -g color1)
bspc config normal_border_color "$inactive"
bspc config focused_border_color "$inactive"
# bspc config focused_border_color "$inactive"
bspc config presel_feedback_color "$inactive"

# startup
~/.fehbg &
# hsetroot -solid $(getxres background)
~/.config/polybar/launch.sh &
picom &
mpDris2 & 
pulseeffects --gapplication-service &
dunst &
# pgrep xflux || xflux -l 43.36 -g 1.26 &
udiskie &
pkill 2bspwm ; 2bspwm &
pkill flashfocus ; flashfocus &
