#! /bin/sh

# wm config
bspc config border_width 1
bspc config window_gap 10
out=0
# bspc config top_padding $(( $(polybar --dump=height base 2>/dev/null) + $(polybar --dump=offset-y base 2>/dev/null)+ $out + $(bspc config window_gap)))
bspc config top_padding $(( $(polybar --dump=height base 2>/dev/null) + $(polybar --dump=offset-y base 2>/dev/null)+ $out))
bspc config split_ratio          0.50

bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# rules
bspc rule -a Zathura state=tiled

inactive=$(colorer -g bg)
active=$(colorer -g color8)
bspc config normal_border_color "$inactive"
bspc config focused_border_color "$active"
# bspc config focused_border_color "$inactive"
bspc config presel_feedback_color "$inactive"

# startup
pgrep sxhkd || sxhkd -m 1 &

~/.fehbg &
# hsetroot -solid $(getxres background)
# ~/.config/polybar/launch.sh &
pgrep polybar || polybar -r &
pgrep picom || picom -b &
# mpDris2 & 
# pulseeffects --gapplication-service &
pkill dunst; dunst &
# pgrep xflux || xflux -l 43.36 -g 1.26 &
pgrep udiskie || udiskie &
# pkill 2bspwm ; 2bspwm &
pkill flashfocus ; flashfocus &
pgrep xfce4-power-manager || xfce4-power-manager &
pm2 describe fmcord || pm2 start --cwd="/home/louise/Code/fmcord" --name=fmcord app.js &
pgrep xsettingsd || xsettingsd &
