#!/bin/sh
# $1: +/-
# $2: padding to add/remove
# $3: bar position
# $4: padding for the bar

for i in left bottom right top
do
    bspc config -d focused "${i}_padding" $(( $(bspc config -d focused "${i}_padding") $1 $2 ))
    [[ $(bspc config -d focused ${i}_padding) -lt 0 ]] && bspc config -d focused ${i}_padding 0
done

#[[ $(bspc config -d focused ${3}_padding) -lt $4 ]] && bspc config -d focused ${3}_padding $4 


