#! /bin/sh

sxhkd &

# wm config
bspc config border_width         2
bspc config window_gap 20

bspc config split_ratio          0.52

bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI VII VIII IX X

# rules
bspc rule -a Zathura state=tiled
bspc rule -a "Genymotion Player" state=floating

# startup
~/.config/polybar/launch.sh &
picom -b --experimental-backends &
wal -R
~/.fehbg
dunst &
# feh-blur -d &
xflux -l 43.36 -g 1.26 &
disown

# source pywal colors
. "$HOME/.cache/wal/colors.sh"
bspc config normal_border_color $color6
bspc config focused_border_color $color14
bspc config presel_feedback_color $color14
