#! /bin/sh

sxhkd &

# wm config
bspc config border_width         0
bspc config border_radius        0
bspc config window_gap 20

bspc config split_ratio          0.52

bspc config focus_follows_pointer true

bspc monitor -d I II III IV V VI VII VIII

# rules
bspc config external_rules_command "$HOME/.config/bspwm/external_rules"
bspc rule -a discord desktop='^7'
bspc rule -a Zathura state=tiled
bspc rule -a "Genymotion Player" state=floating


# startup
~/.config/polybar/launch.sh
compton -b &
wal -R
~/.fehbg
dunst &
feh-blur -d &
xflux -l 43.36 -g 1.26

# source pywal colors
. "$HOME/.cache/wal/colors.sh"
bspc config normal_border_color $color0
bspc config focused_border_color $color7
bspc config presel_feedback_color $color7
