#! /bin/sh

sxhkd &

# wm config
bspc config border_width 4
bspc config window_gap 20
out=0
# outer_gaps =30
bspc config top_padding $(( $(polybar --dump=height base 2>/dev/null) + $out ))
bspc config split_ratio          0.50

bspc config focus_follows_pointer true

bspc monitor -d 1 2 3 4 5

# rules
bspc rule -a Zathura state=tiled
bspc rule -a "Genymotion Player" state=floating
bspc rule -a "fl.exe" state=tiled

inactive=$(getxres color8)
active=$(getxres color1)
bspc config normal_border_color "$inactive"
bspc config focused_border_color "$active"
# bspc config focused_border_color "$inactive"
bspc config presel_feedback_color "$inactive"

# startup
~/.fehbg &
# hsetroot -solid $(getxres background)
# toggle_state floating
~/.config/polybar/launch.sh &
# polybar-autohide &
# phicom2 -b &
picom -b & 
mpDris2 & 
pulseeffects --gapplication-service &
# mpv --loop --wid=0 ~/Downloads/d.gif
dunst &
# feh-blur -d &
# pgrep xflux || xflux -l 43.36 -g 1.26 &
udiskie &
# pkill 2bspwm ; 2bspwm &
# pkill flashfocus ; flashfocus &
# colorer -R
bspc rule -a Lollypop -o desktop=^5
lollypop &

# layout
bsp-layout set tall 1
bsp-layout set tall 2
bsp-layout set tall 3
bsp-layout set tall 4
bsp-layout set tall 5
