#!/bin/bash

# Terminate already running bar instances
killall -q polybar

# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

# i3 bar
if [[ $1 = "i3" ]]; then
polybar -c .config/polybar/i3config -rq 'workspaces'$1 &
polybar -c .config/polybar/i3config -rq music &
polybar -c .config/polybar/i3config -rq tray &
fi

# openbox bar
if [[ $1 = "ob" ]]; then
polybar -c .config/polybar/obconfig -rq music &
polybar -c .config/polybar/obconfig -rq tray &
fi

echo "Polybar launched..."
