#!/bin/bash

# kill other instances
script_name=timemanager
for pid in $(pidof -x $script_name); do
    if [ $pid != $$ ]; then
        kill -9 $pid
		echo "Killed other instance"
    fi
done


while [ true ];
	do
	notify-send -u critical -t 3000 "time manager" "$(uptime -p)"
	sleep 30m;
	done
