#!/usr/bin/env python3
import sys
import subprocess


def get(str):
    try:
        return subprocess.check_output(str, shell=True).decode('utf-8').replace('\n', '')
    except:
        return ""


def getpol(key, bar):
    str = "polybar --dump={} {} 2>/dev/null".format(key, bar)
    return get(str)


def getctl(format):
    global player
    str = "playerctl metadata --format {{{{{}}}}} -p {} 2>/dev/null".format(
        format, player)
    return get(str)


player = sys.argv[1]
play_icon = sys.argv[2]
pause_icon = sys.argv[3]
prev_icon = sys.argv[4]
next_icon = sys.argv[5]
logo_icon = sys.argv[6]
strlen = int(sys.argv[7])

if getctl('status') == "Playing":
    color = getpol('foreground', 'base')
else:
    color = getpol('line-color', 'base')

artist = getctl('artist')
title = getctl('title')
total_length = len(artist) + len(title) + 2

if total_length > strlen:
    difference = total_length-strlen
    title = title[:-difference] + '…'
    total_length = len(artist) + len(title) + 1
    if total_length > strlen:
        difference = total_length-strlen
        artist = artist[:-difference]

if getctl('status') == "Playing":
    status = pause_icon
else:
    status = play_icon

# Formatting the string
strlogo = "%{F" + color + "}" + logo_icon
strartist = "%{T2}" + artist + ":%{T-}"
strtitle = title
strprev = "%{F-}%{A1:playerctl previous -p " + \
    player + ":}" + prev_icon + "%{A}"
strplaypause = "%{A1:playerctl play-pause -p " + \
    player + ":}" + status + "%{A}"
strnext = "%{A1:playerctl next -p " + player + ":}" + next_icon + "%{A}"

print(strlogo, strartist, strtitle, strprev, strplaypause, strnext)
